# Site settings
title: Steve &amp; Amanda Get Married!
email: us@SteveAmandaGetMarried.info

# description: > # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.

# the subpath of your site, e.g. /blog/
baseurl: ""
url: "http://steveamandagetmarried.info"
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown


defaults:
  -
    scope:
      path: ""
    values:
      site.email: "us@steveamandagetmarried.info"